/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/desktop/AppIcon.vue')['default']
    AppWindow: typeof import('./src/components/desktop/AppWindow.vue')['default']
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardAction: typeof import('./src/components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Checkbox: typeof import('./src/components/ui/checkbox/Checkbox.vue')['default']
    ConnectionPanel: typeof import('./src/components/ConnectionPanel.vue')['default']
    DesktopDock: typeof import('./src/components/desktop/DesktopDock.vue')['default']
    DesktopIcon: typeof import('./src/components/desktop/DesktopIcon.vue')['default']
    DesktopIcons: typeof import('./src/components/desktop/DesktopIcons.vue')['default']
    DesktopStatusBar: typeof import('./src/components/desktop/DesktopStatusBar.vue')['default']
    DesktopWallpaper: typeof import('./src/components/desktop/DesktopWallpaper.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./src/components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    ScrollArea: typeof import('./src/components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./src/components/ui/scroll-area/ScrollBar.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    Slider: typeof import('./src/components/ui/slider/Slider.vue')['default']
    Switch: typeof import('./src/components/ui/switch/Switch.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    Toast: typeof import('./src/components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./src/components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./src/components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./src/components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./src/components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./src/components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./src/components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./src/components/ui/toast/ToastViewport.vue')['default']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
    TrafficLights: typeof import('./src/components/desktop/TrafficLights.vue')['default']
  }
}
